theme: jekyll-theme-cayman
title: Ifeoma Onuobia Helen
description: Data Analyst | Excel • Power BI • SQL • Tableau | Executive Administrative Asisitant | Operations | Turning Data into Actionable Insights
