theme: jekyll-theme-minimal
title: Ifeoma Onuobia Helen
logo: WhatsApp Image 2026-01-14 at 1.21.43 PM.jpeg
description: Data Analyst | Excel • Power BI • SQL • Tableau | Executive Administrative Asisitant | Operations | Turning Data into Actionable Insights
